seasons:
  live: "2025-2026"
  benchmark: "2024-2025"

sources:
  fbref:
    standard:
      url: "https://fbref.com/en/comps/20/stats/Bundesliga-Stats"
      table_id: "stats_standard"
    shooting:
      url: "https://fbref.com/en/comps/20/shooting/Bundesliga-Stats"
      table_id: "stats_shooting"
    passing:
      url: "https://fbref.com/en/comps/20/passing/Bundesliga-Stats"
      table_id: "stats_passing"
    possession:
      url: "https://fbref.com/en/comps/20/possession/Bundesliga-Stats"
      table_id: "stats_possession"
    defending:
      url: "https://fbref.com/en/comps/20/defense/Bundesliga-Stats"
      table_id: "stats_defense"

output:
  raw_dir: "data/raw"
  request_pause_seconds: 7
  html_cache_dir: "data/html_cache"
  use_html_cache: true


#output:
 # raw_dir: "data/raw"
 # user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
 # request_pause_seconds: 7
 # retries_on_403: 0
 # sleep_on_403_seconds: 60
 # retries_total: 4
 # retry_backoff_factor: 2.0

